### ISSUE TITLE
Keep rspec folder only for tests

### ISSUE THREAD

**Issue by olivierobert** [fikrikarim/ud3my#3]
It seems like you focused on creating rspec test so there is no need to keep the default minitest specs folder. Keep only what you need from the default setup.

<img width="275" alt="ud3my___volumes_workspace__candidates-tests_ud3my__-_____spec_support_login_macros_rb__ud3my_" src="https://user-images.githubusercontent.com/696529/38172007-b71174e8-35ce-11e8-8bfe-ddeee28a2b28.png">

**Comment by fikrikarim** [comment]
Thanks! I forgot to remove the test folder.

I have fixed the issue on commit 8e728f143c0eef0b547f5cd6ce81b9c198ebb47d.

Please reopen the issue if you feel necessary.
