### ISSUE TITLE
Improvement - Use  Warden::Test::Helpers to login users programmaticaly (faster tests 🚀)

### ISSUE THREAD

**Issue by olivierobert** [fikrikarim/ud3my#4]
Creating helpers for repetitive processes in feature tests was a good call. But logging in users manually (through the login form) takes loads of time. 

Instead, use `login_as`from [Warden::Test::Helpers](https://github.com/plataformatec/devise/wiki/How-To:-Test-with-Capybara) to login users programmatically (i.e. without going through the form).

**Comment by fikrikarim** [comment]
Oh great I didn't know that.

On this commit 89b5b2d01433d0aa75879370a2db053e48b180ea I've fixed this issue by changing the login macro on group_spec, static_page_spec, and user_spec to use the login_as method from warden test helpers.

I've left the devise_spec using `login` macro for testing the manual login process (through the login form).

Please reopen the issue if you feel necessary.
