### ISSUE TITLE
Improvement - DRYer Pundit Policies 

### ISSUE THREAD

**Issue by olivierobert** [fikrikarim/ud3my#6]
<img width="333" alt="ud3my___volumes_workspace__candidates-tests_ud3my__-_____app_policies_group_policy_rb__ud3my_" src="https://user-images.githubusercontent.com/696529/38172107-60227158-35d0-11e8-8a73-a979bb07db88.png">

Currently, there are lots of code repetition in policies which would be avoided using method alias:

```ruby
def manage?
  user.instructor?
end

alias index? manage?
alias new? manage?
alias edit? manage?
alias create? manage?
alias update? manage?
alias destroy? manage?
```

**Comment by fikrikarim** [comment]
Yeah I had searched for methods or ways to make the policies looked cleaner and DRYer. Then I stumbled upon an article or stackoverflow question (sorry couldn't find the link) that said I should write the policies as explicit as possible, to make the policy easy to read and good for documentation.

But I guess using `alias` method is explicit enough, and it makes the code looks much cleaner.

I've fixed the issue on commit e9a5666a6e2d915b0c83884ebb438fdd82113e1a

Please reopen the issue whenever you feel necessary.
